# Generated by Django 4.2.7 on 2023-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_chat_id',
            field=models.IntegerField(default=0, max_length=20, verbose_name='chat_id в телеграме'),
        ),
    ]
