# Generated by Django 4.2.7 on 2023-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_t_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='t_chat_id',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(default=0, max_length=20, verbose_name='chat_id в телеграме'),
        ),
    ]
