# Generated by Django 4.2.7 on 2023-11-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('time', models.DurationField(verbose_name='время')),
                ('date', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место')),
                ('is_nice', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('associated_habit', models.CharField(blank=True, max_length=150, null=True,
                                                      verbose_name='связанная привычка')),
                ('periodicity', models.IntegerField(verbose_name='переодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_do', models.PositiveIntegerField(verbose_name='время на выполнение')),
                ('is_publish', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
