# Generated by Django 4.2.7 on 2023-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(verbose_name='переодичность(количество повторений в неделю)'),
        ),
    ]
